print("hellow coders")
print("welcome to coders words")

# HI THIS IS OUR FIRST PROGRAMMING OF PAYTHON

""""
this is multiline comments systemn
this is the rule

"""
# Data type , variable , conditions , loop

# Data type


print(type(10))
print(type(10.50))
print(type('a'))
print(type("name"))
print(type(True))
print(type(False))


#Variable
number = 100
number2 = 100.50
string1 ='a'
string2 ="bool"
is_True = True
is_False = False

print(number, type(number),id(number))
print(number2, type(number2))
print(string1, type('string1'))
print(string2,type("string2"))
print(is_True, type(is_True))
print(is_False, type(is_False))